backend:
  name: github
  repo: bryanbtd/brainstormingdigital
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Título", widget: "string" }
          - { name: "content", label: "Contenido", widget: "markdown" }
          
