backend:
  name: git-gateway
  branch: main  # Asegúrate que coincida con tu rama principal

media_folder: "assets/uploads"  # Carpeta para subir imágenes
public_folder: "/assets/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - name: "home"
        label: "Inicio"
        file: "index.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "body", widget: "markdown"}
