backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Crear {{collection}} “{{slug}}”"
    update: "Actualizar {{collection}} “{{slug}}”"

# Añade esta configuración de roles:
publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
