backend:
  name: github
  repo: bryanbtd/brainstormingdigital  # Tu usuario/repo
  branch: main  # Asegúrate de que sea "main" o "master"
media_folder: "images"  # Carpeta donde subirás imágenes
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.md"  # O "index.html" si usas HTML
        fields:
          - { name: "title", label: "Título", widget: "string" }
          - { name: "body", label: "Contenido", widget: "markdown" }
